[tool.ruff]
line-length = 100

select = [
	"E",    # pycodestyle errors
	"F",    # pyflakes
	"B",    # flake8-bugbear
	"I",    # isort
	"UP",   # pyupgrade
	"C90",  # mccabe (complexity)
	"N",    # pep8-naming
	"D",    # pydocstyle (docstring)
	"S",    # flake8-bandit (security)
	"A",    # flake8-builtins
	"C4",   # flake8-comprehensions
	"T20",  # flake8-print
	"Q",    # flake8-quotes
	"RUF"   # ruff-specific rules
]

ignore = [
	"D100",  # Missing docstring in public module
	"D104",  # Missing docstring in public package
	"D107"   # Missing docstring in __init__
]

[tool.ruff.isort]
known-first-party = ["your_package_name"]
combine-as-imports = true

[tool.ruff.flake8-bugbear]
extend-immutable-calls = []
